### Add contact (POST) POST http://localhost:3001/users Content-Type: application/json

{
   
    "firstName": "Alina",
    "lastName": "Hernández",
    "email": "ah@hernandez.net",
    "favoriteColor": "Green",
    "birthday": "6/6/1996"
  }

### Update contact (PUT) PUT http://localhost:3001/users/6673d30bc218423e96a18b66 Content-Type: application/json
  {
    
    "firstName": "Charlie",
    "lastName": "Brown",
    "email": "charlie.brown@example.com",
    "favoriteColor": "Golden",
    "birthday": "1995-03-25"
  }
### Delete Contact DELETE http://localhost:3001/users



// PRODUCTION ### GET home GET https://project1-arj6.onrender.com

### GET all contacts GET https://project1-arj6.onrender.com/users

### GET specific contact GET https://project1-arj6.onrender.com/users/6673d30bc218423e96a18b66

### Add contact (POST contact) POST https://cse341-contacts-6y6j.onrender.com/users Content-Type: application/json

  {
    
    "firstName": "Alina",
    "lastName": "Hernández",
    "email": "ah@hernandez.net",
    "favoriteColor": "Green",
    "birthday": "6/6/1996"
  }
### Change contact information (PUT) PUT https://cse341-contacts-6y6j.onrender.com/users Content-Type: application/json

  {
    
    "firstName": "Charlie",
    "lastName": "Brown",
    "email": "charlie.brown@example.com",
    "favoriteColor": "Golden",
    "birthday": "1995-03-25"
  }
### Remove a contact (DELETE) DELETE https://cse341-contacts-6y6j.onrender.com/users